CREATE TABLE named (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(256) NOT NULL
);

CREATE TABLE folders (
    FID INT NOT NULL PRIMARY KEY,
    PARENT_ID INT,

    FOREIGN KEY (FID) REFERENCES named(ID),
    FOREIGN KEY (PARENT_ID) REFERENCES folders(FID)
);

CREATE TABLE pictures (
    PID INT NOT NULL PRIMARY KEY,
    FOLDER_ID INT NOT NULL,
    TIMESTAMP TIMESTAMP NOT NULL,
    WIDTH INT NOT NULL,
    HEIGHT INT NOT NULL,
    LATITUDE DOUBLE,
    LONGITUDE DOUBLE,
    ALTITUDE DOUBLE,

    FOREIGN KEY (PID) REFERENCES named(ID),
    FOREIGN KEY (FOLDER_ID) REFERENCES folders(FID)
);

CREATE TABLE picture_tags (
    PICTURE_ID INT NOT NULL,
    INDEX INT NOT NULL,
    NAME VARCHAR(256) NOT NULL,

    PRIMARY KEY (PICTURE_ID,INDEX),
    FOREIGN KEY (PICTURE_ID) REFERENCES pictures(PID)
);

CREATE INDEX picture_tags_name ON picture_tags(NAME);

CREATE TABLE picture_descriptions (
    PICTURE_ID INT NOT NULL,
    LANGUAGE VARCHAR(4) NOT NULL,
    DESCRIPTION TEXT NOT NULL,

    PRIMARY KEY (PICTURE_ID,LANGUAGE),
    FOREIGN KEY (PICTURE_ID) REFERENCES pictures(PID)
);

-- Initial data

INSERT INTO named(NAME)
    VALUES('root');
INSERT INTO folders(FID, PARENT_ID)
    VALUES((SELECT ID FROM named WHERE NAME='root'), NULL);
INSERT INTO named(NAME)
    VALUES('sub1');
INSERT INTO folders(PARENT_ID,FID)
    VALUES((SELECT ID FROM named WHERE NAME='root'), 
    (SELECT ID FROM named WHERE NAME='sub1'));
INSERT INTO named(NAME)
    VALUES('sub2');
INSERT INTO folders(PARENT_ID,FID)
    VALUES((SELECT ID FROM named WHERE NAME='root'), 
    (SELECT ID FROM named WHERE NAME='sub2'));
